<?php

/**
 * This is the model base class for the table "raza".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Raza".
 *
 * Columns in table "raza" available as properties of the model,
 * followed by relations of table "raza" available as properties of the model.
 *
 * @property integer $id_raza
 * @property integer $id_especie
 * @property string $nombre_raza
 *
 * @property Especie $idEspecie
 */
abstract class BaseRaza extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'raza';
    }

    public static function representingColumn() {
        return 'nombre_raza';
    }

    public function rules() {
        return array(
            array('id_especie, nombre_raza', 'required'),
            array('id_especie', 'numerical', 'integerOnly'=>true),
            array('nombre_raza', 'length', 'max'=>1024),
            array('id_raza, id_especie, nombre_raza', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idEspecie' => array(self::BELONGS_TO, 'Especie', 'id_especie'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_raza' => Yii::t('app', 'Id Raza'),
                'id_especie' => Yii::t('app', 'Id Especie'),
                'nombre_raza' => Yii::t('app', 'Nombre Raza'),
                'idEspecie' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_raza', $this->id_raza);
        $criteria->compare('id_especie', $this->id_especie);
        $criteria->compare('nombre_raza', $this->nombre_raza, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}