<?php

/**
 * This is the model base class for the table "noticia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Noticia".
 *
 * Columns in table "noticia" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_noticia
 * @property string $titulo
 * @property string $fecha_publicacion
 * @property string $cuerpo
 * @property string $image
 *
 */
abstract class BaseNoticia extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'noticia';
    }

    public static function representingColumn() {
        return 'fecha_publicacion';
    }

    public function rules() {
        return array(
            array('fecha_publicacion', 'required'),
            array('titulo', 'length', 'max'=>100),
            array('image', 'length', 'max'=>128),
            array('cuerpo', 'safe'),
            array('titulo, cuerpo, image', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_noticia, titulo, fecha_publicacion, cuerpo, image', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_noticia' => Yii::t('app', 'Id Noticia'),
                'titulo' => Yii::t('app', 'Titulo'),
                'fecha_publicacion' => Yii::t('app', 'Fecha Publicacion'),
                'cuerpo' => Yii::t('app', 'Cuerpo'),
                'image' => Yii::t('app', 'Image'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_noticia', $this->id_noticia);
        $criteria->compare('titulo', $this->titulo, true);
        $criteria->compare('fecha_publicacion', $this->fecha_publicacion, true);
        $criteria->compare('cuerpo', $this->cuerpo, true);
        $criteria->compare('image', $this->image, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}