<?php

/**
 * This is the model base class for the table "especie".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Especie".
 *
 * Columns in table "especie" available as properties of the model,
 * followed by relations of table "especie" available as properties of the model.
 *
 * @property integer $id_especie
 * @property string $nombre_especie
 *
 * @property Animal[] $animals
 * @property Raza[] $razas
 */
abstract class BaseEspecie extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'especie';
    }

    public static function representingColumn() {
        return 'nombre_especie';
    }

    public function rules() {
        return array(
            array('nombre_especie', 'required'),
            array('nombre_especie', 'length', 'max'=>1024),
            array('id_especie, nombre_especie', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'animals' => array(self::HAS_MANY, 'Animal', 'id_especie'),
            'razas' => array(self::HAS_MANY, 'Raza', 'id_especie'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_especie' => Yii::t('app', 'Id Especie'),
                'nombre_especie' => Yii::t('app', 'Nombre Especie'),
                'animals' => null,
                'razas' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_especie', $this->id_especie);
        $criteria->compare('nombre_especie', $this->nombre_especie, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}